version: '3.8'

services:
  backend:
    image: timac11/image-gallery-back:latest
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - sqlite_data:/app/system/db.sqlite3

  ui:
    image: timac11/image-gallery-ui:latest
    ports:
      - "80:80"

volumes:
  sqlite_data:
    driver: local
