# Generated by Django 5.1.2 on 2024-11-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
